# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EggMeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'KakaoSDKCommon'
pod 'DropDown', '2.3.13'
pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'DLRadioButton', '~> 1.4'
pod 'Starscream'
pod 'StompClientLib'
pod 'Tabman', '~> 2.9'
pod 'IQKeyboardManagerSwift'
pod 'FSCalendar'


# Pods for EggMeet
end
